site_name: RoBaertschi
site_url: https://robaertschi.github.io

theme: material

nav:
  - Home: 'index.md'
  - About Me: 'aboutme.md'
  - Projects: 
    - Projects: 'projects.md'
    - Minetech:
      - Minetech: 'minetech/minetech.md'
      - API (WIP): 'minetech/api.md'
