site_name: RoBaertschi
site_url: https://robaertschi.github.io

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - About Me: 'aboutme.md'
  - Projects: 
    - Projects: 'projects.md'
